spring:
  profiles:
    active: dev

camel:

    springboot:
         main-run-controller: true

    component:
        kafka:
            brokers: localhost:9092
            consumer-group-id: persistence

mongo:
   port: 27017
   host: localhost
